// <auto-generated />
using EndemicGardening.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EndemicGardening.Migrations
{
    [DbContext(typeof(PlantContext))]
    partial class PlantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EndemicGardening.Models.BioPolygon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BioPolys");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GroupName = "Limestone Fynbos",
                            Name = "Agulhas Limestone Fynbos"
                        });
                });

            modelBuilder.Entity("EndemicGardening.Models.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bee")
                        .HasColumnType("bit");

                    b.Property<int>("BiomeID")
                        .HasColumnType("int");

                    b.Property<bool>("Bird")
                        .HasColumnType("bit");

                    b.Property<bool>("Butterfly")
                        .HasColumnType("bit");

                    b.Property<string>("ConservationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Edible")
                        .HasColumnType("bit");

                    b.Property<bool>("Flower")
                        .HasColumnType("bit");

                    b.Property<string>("PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tips")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Bee = true,
                            BiomeID = 2,
                            Bird = false,
                            Butterfly = true,
                            ConservationStatus = "NT",
                            Descript = "A beautiful dwarf perennial with blue, cinnamon-scented flowers in spring, that is an attractive garden subject and can be planted in a sunny rockery.",
                            Edible = true,
                            Flower = true,
                            PicUrl = "https://cdn.pixabay.com/photo/2019/10/26/05/31/flower-4578712_960_720.jpg",
                            PlantName = "Babiana fragrans",
                            Tips = "Seeds must be sown in autumn (March), planted in a sifted mixture of soil/sand and compost (50/50), and covered with soil that is equal in depth to the diameter of the seed. It must be planted in a deep seed tray because, as the seedling grows, it will pull itself down. To maximize percentage germination, the seeds can be leached, scarified or soaked. Soil must be kept moist until germination, which will take 6 weeks or longer."
                        },
                        new
                        {
                            PlantId = 2,
                            Bee = false,
                            BiomeID = 3,
                            Bird = true,
                            Butterfly = true,
                            ConservationStatus = "N",
                            Descript = "Aloe marlothii is a striking, robust, large, single-stemmed aloe with a majestic presence. ",
                            Edible = false,
                            Flower = true,
                            PicUrl = "https://cdn.pixabay.com/photo/2020/05/25/12/50/aloe-5218483_960_720.jpg",
                            PlantName = "Aloe marlothii",
                            Tips = "Aloe marlothii will grow easily and with very little care in most South African gardens and is recommended for gardens where the species occurs naturally."
                        },
                        new
                        {
                            PlantId = 3,
                            Bee = false,
                            BiomeID = 5,
                            Bird = true,
                            Butterfly = true,
                            ConservationStatus = "LC",
                            Descript = "Gloriosa superba is a deciduous, summer-growing climber up to 1.5 m tall, with tuberous roots.",
                            Edible = false,
                            Flower = true,
                            PicUrl = "https://cdn.pixabay.com/photo/2015/11/10/09/23/south-africa-1036552_960_720.jpg",
                            PlantName = "Gloriosa superba",
                            Tips = "Gloriosa superba has weak stems and uses other plants for support, climbing by means of the tendrils at its leaf tips, which cling to shrubs and trees that they touch."
                        },
                        new
                        {
                            PlantId = 4,
                            Bee = false,
                            BiomeID = 5,
                            Bird = true,
                            Butterfly = true,
                            ConservationStatus = "N",
                            Descript = "Silk Acacia",
                            Edible = false,
                            Flower = true,
                            PicUrl = "https://cdn.pixabay.com/photo/2013/01/05/13/17/acacia-flowers-73866_960_720.jpg",
                            PlantName = "Acacia Tree",
                            Tips = "Do not overwater."
                        },
                        new
                        {
                            PlantId = 5,
                            Bee = false,
                            BiomeID = 1,
                            Bird = true,
                            Butterfly = true,
                            ConservationStatus = "N",
                            Descript = "Mandela's gold",
                            Edible = false,
                            Flower = true,
                            PicUrl = "https://cdn.pixabay.com/photo/2013/12/30/22/24/flower-236008__340.jpg",
                            PlantName = "Strelitzia reginae",
                            Tips = "Ideal conditions are full sun, rich, well-drained loam soil with a pH of approximately 7.5, regular deep watering in summer and liberal applications of fertilizer in early summer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
